### ISSUE TITLE
[Bug 🐛]: Vivaldi - Tabs close by themselves

### ISSUE THREAD

**Issue by xchatter** [borsini/chrome-otto-tabs#24]
### What happened?

Sometimes when I open some new tab part of particular domain and have several already opened within the realm of the same domain, some tabs close by themselves.

### What should happen?

Tabs shouldn't be closing by themselves

### Version

4.2

### What browsers are you seeing the problem on?

Vivaldi

**Comment by borsini** [comment]
Hello, this behavior is a feature of Otto Tabs described [here](https://github.com/borsini/chrome-otto-tabs?tab=readme-ov-file#remove-older-tabs).

You can switch it off by clicking on the extension icon and unchecking the corresponding checkbox.
<img width="433" alt="Capture d’écran 2024-05-05 à 22 04 56" src="https://github.com/borsini/chrome-otto-tabs/assets/22218860/01a79bae-fe6e-4c99-97d3-496934082a21">
