### ISSUE TITLE
Tabs in stacks closing on browser restart if more than 5 [Vivaldi]

### ISSUE THREAD

**Issue by ayush-km** [borsini/chrome-otto-tabs#7]
Even though the last setting is turned off, the stacks with more than 5 tabs to get their tabs reduced to 4 on browser restart.
Please fix this.
![image](https://user-images.githubusercontent.com/57125345/121320234-6677ce80-c926-11eb-8319-e7a0d9b71831.png)

**Comment by borsini** [comment]
fixed in #13 with the use of the service worker
